const mongoose = require('mongoose');

const emailSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  from: String,
  to: String,
  subject: String,
  body: String,
  aiReply: String, // generated by AI
  date: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Email', emailSchema);
